- name: Deploy to App Engine
  uses: google-github-actions/deploy-appengine@v0.2.0
  with:
    deliverables: app.qa.yaml
    project_id: ${{ secrets.GCP_PROJECT_QA }}
    credentials: ${{ secrets.GCP_SA_KEY }}