on:
  push:
    branches:
      - main

name: Deploy to Google App Engine PROD

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Google Cloud Functions
        id: deploy-gcf
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: UpdateMemberMetrics
          runtime: go113
          env_vars_file: cloudfunctions.yaml
          project_id: ${{ secrets.GCF_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: ${{ secrets.TOPIC }}
          event_trigger_service: pubsub.googleapis.com