on:
  push:
    branches:
      - qa

name: Deploy to Google App Engine QA Environment

jobs:
  deploy:
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.qa.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}